name: solarium_mason
description: Library of utilities to help build SolariumVR sites.
version: 0.0.1
homepage: https://solariumvr.com
author: Michael Francis<michael@solariumvr.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async: "^1.13.3"
  path: "^1.4.2"

dev_dependencies:
  test: ^0.12.0
